/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BingLogo: typeof import('./../src/.vuepress/components/BingLogo/index.vue')['default']
    BlogClock: typeof import('./../src/.vuepress/components/BlogClock/index.vue')['default']
    CompressImage: typeof import('./../src/.vuepress/components/tools/CompressImage/index.vue')['default']
    CssTriangleGenerator: typeof import('./../src/.vuepress/components/tools/CssTriangleGenerator/index.vue')['default']
    DotLottie: typeof import('./../src/.vuepress/components/DotLottie/index.vue')['default']
    GeneratorColor: typeof import('./../src/.vuepress/components/tools/CssTriangleGenerator/GeneratorColor.vue')['default']
    GeneratorDirection: typeof import('./../src/.vuepress/components/tools/CssTriangleGenerator/GeneratorDirection.vue')['default']
    GeneratorOption: typeof import('./../src/.vuepress/components/tools/CssTriangleGenerator/GeneratorOption.vue')['default']
    GeneratorPreview: typeof import('./../src/.vuepress/components/tools/CssTriangleGenerator/GeneratorPreview.vue')['default']
    GeneratorSize: typeof import('./../src/.vuepress/components/tools/CssTriangleGenerator/GeneratorSize.vue')['default']
    Heatmap: typeof import('./../src/.vuepress/components/Heatmap/index.vue')['default']
    InfoPanel: typeof import('./../src/.vuepress/components/InfoPanel/index.vue')['default']
    MacKeyboard: typeof import('./../src/.vuepress/components/MacKeyboard/index.vue')['default']
    NaiveProvider: typeof import('./../src/.vuepress/components/NaiveProvider/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    PageFooter: typeof import('./../src/.vuepress/components/PageFooter/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortVideoRemoveWatermark: typeof import('./../src/.vuepress/components/tools/ShortVideoRemoveWatermark/index.vue')['default']
    SponsorButton: typeof import('./../src/.vuepress/components/SponsorButton/index.vue')['default']
    TravellingLink: typeof import('./../src/.vuepress/components/TravellingLink/index.vue')['default']
  }
}
