/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BingLogo: typeof import('./../src/.vuepress/components/BingLogo/index.vue')['default']
    BlogClock: typeof import('./../src/.vuepress/components/BlogClock/index.vue')['default']
    CssTriangleGenerator: typeof import('./../src/.vuepress/components/CssTriangleGenerator/index.vue')['default']
    DotLottie: typeof import('./../src/.vuepress/components/DotLottie/index.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    GeneratorColor: typeof import('./../src/.vuepress/components/CssTriangleGenerator/GeneratorColor.vue')['default']
    GeneratorDirection: typeof import('./../src/.vuepress/components/CssTriangleGenerator/GeneratorDirection.vue')['default']
    GeneratorOption: typeof import('./../src/.vuepress/components/CssTriangleGenerator/GeneratorOption.vue')['default']
    GeneratorPreview: typeof import('./../src/.vuepress/components/CssTriangleGenerator/GeneratorPreview.vue')['default']
    GeneratorSize: typeof import('./../src/.vuepress/components/CssTriangleGenerator/GeneratorSize.vue')['default']
    Heatmap: typeof import('./../src/.vuepress/components/Heatmap/index.vue')['default']
    InfoPanel: typeof import('./../src/.vuepress/components/InfoPanel/index.vue')['default']
    MacKeyboard: typeof import('./../src/.vuepress/components/MacKeyboard/index.vue')['default']
    PageFooter: typeof import('./../src/.vuepress/components/PageFooter/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TravellingLink: typeof import('./../src/.vuepress/components/TravellingLink/index.vue')['default']
  }
}
